extends MainLoop

# DO NOT EDIT THIS FILE DIRECTLY
# Generated via convo_parser.py, and used to generate tres file.

# .zshrc has alias /Applications/Godot4.4.app/Contents/MacOS/Godot
# Run with godot4 --headless --script res://dialog/tools/SCRIPT.gd
func _initialize():
	print("Generating dialogs...")
	var res = build()
	ResourceSaver.save(res, "res://dialog/SCRIPT.tres")
	print("Saved dialog.tres")

func _process(_delta):
	return true

func build():
	var collection = DialogTreeCollection.new()
	var trees: Dictionary[String, DialogState] = {}
	trees["them"] = DialogState.create(
		'them',
		['🤔', 'chilly', 'Who is this...', "You're feeling pretty tired"],
		['My name is Thelma', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
		['My name is Thelma', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
		[
			DialogState.create(
				'Eucl',
				[],
				['Response'],
				['Response'],
				[
					null
				],
				[],
			),
			DialogState.create(
				'Eucl',
				['dir 1'],
				["I know you're Thelma"],
				["I know you're Thelma"],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Sophie"] = DialogState.create(
		'Sophie',
		[],
		['A', 'A!!!', 'A?'],
		['A', 'A!!!', 'A?'],
		[
			DialogState.create(
				'Eucl',
				[],
				['B'],
				['B\nB!!'],
				[
					DialogState.create(
						'Sophie',
						[],
						['C', 'D'],
						['C', 'D'],
						[
							DialogState.create(
								'Eucl',
								[],
								['E'],
								['E'],
								[
									null
								],
								[],
							),
							DialogState.create(
								'Eucl',
								[],
								['F'],
								['F\nG'],
								[
									null
								],
								[],
							),
						],
						[],
					),
				],
				[],
			),
			DialogState.create(
				'Eucl',
				[],
				['b...'],
				['b...'],
				[
					null
				],
				[],
			),
			DialogState.create(
				'Eucl',
				[],
				['B.'],
				['B.'],
				[
					DialogState.create(
						'Sophie',
						[],
						['mmm.', 'mmmmm...'],
						['mmm.', 'mmmmm...\nmm?'],
						[
							DialogState.create(
								'Eucl',
								[],
								['C'],
								['C'],
								[
									null
								],
								[],
							),
							DialogState.create(
								'Eucl',
								[],
								['!!!'],
								['!!!'],
								[
									DialogState.create(
										'Sophie',
										[],
										['mmmm...'],
										['mmmm...'],
										[
											null
										],
										[],
									),
								],
								[],
							),
						],
						[],
					),
				],
				[],
			),
		],
		[],
	)
	collection.trees = trees
	return collection
